package com.helphub.backend.modules.postreaction;

import com.helphub.backend.common.enums.PostReactionType;
import com.helphub.backend.common.enums.PostStatus;
import com.helphub.backend.common.enums.PostVisibility;
import com.helphub.backend.common.enums.UserRole;
import com.helphub.backend.common.exception.BadRequestException;
import com.helphub.backend.common.exception.ForbiddenException;
import com.helphub.backend.common.exception.ResourceNotFoundException;
import com.helphub.backend.modules.postreaction.dto.request.CreatePostReactionRequest;
import com.helphub.backend.modules.postreaction.dto.request.UpdatePostReactionRequest;
import com.helphub.backend.modules.postreaction.dto.response.PostReactionCountResponse;
import com.helphub.backend.modules.postreaction.dto.response.PostReactionResponse;
import com.helphub.backend.persistence.entity.Post;
import com.helphub.backend.persistence.entity.PostReaction;
import com.helphub.backend.persistence.entity.PostReactionId;
import com.helphub.backend.persistence.entity.User;
import com.helphub.backend.persistence.repository.PostReactionRepository;
import com.helphub.backend.persistence.repository.PostRepository;
import com.helphub.backend.persistence.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.UUID;
